name: Update Timetable Data - Force

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-timetable:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the last 2 commits to compare changes
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 cloudscraper asyncpg psycopg2

      - name: Set up environment variables
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV

      - name: Generate new timetable data
        run: python scripts/scrape_timetable.py --output public/classes.csv
      
      - name: Delete debug files
        run: rm -rf debug_page.html

      - name: Commit and push CSV changes
        continue-on-error: true
        run: |
          git config user.name "Taha Parker via GitHub Actions"
          git config user.email "98612931+tahayparker@users.noreply.github.com"
          git add public/classes.csv
          git commit -m "Update timetable CSV data [force]"
          git push

      - name: Initialize the DB
        continue-on-error: true
        run: python scripts/upload_timetable.py
        
      - name: Check for JSON file and generate if needed
        id: check_json
        run: |
            python scripts/generate_schedule.py
        
      - name: Commit and push JSON changes
        run: |
          git config user.name "Taha Parker via GitHub Actions"
          git config user.email "98612931+tahayparker@users.noreply.github.com"
          git add -A
          git commit -m "Update timetable JSON data [force]"
          git push
